#!/bin/bash

set -e
source "$(which shlog)"

typeset -Axg EXT_TO_RENDER_PREFIX=(
    [sh]="## \?"
    [zsh]="## \?"
    [bash]="## \?"
    [java]="\*\* \?"
    [cpp]="\*\* \?"
)

usage () {
    echo "Usage: shrender-prefix [-p PREFIX] <file-to-render>"
}

shrender-prefix() {
    while [[ "$1" = -* ]];do
        case "$1" in
            *) shlog -l error -x 7 "Unknown option '$1' to shrender-prefix" ;;
        esac
        shift
    done
    [[ -z "$1" ]] && { usage; exit; }
    shlog -l trace "Rendering '$1'"
    local renderfile="$1"
    if [[ -z "$INPUT_PREFIX" ]];then
        local ext=${renderfile##*/}
        ext=${ext##*.}
        shlog -l debug "Derive render prefix from extension '$ext'"
        INPUT_PREFIX="${EXT_TO_RENDER_PREFIX[$ext]}"
    fi
    if [[ -z "$INPUT_PREFIX" ]];then
        shlog -l debug "Cannot derive render prefix from '$ext'."
        shlog -l debug "Falling back to renderprefix='##'."
        shlog -l debug "Define EXT_TO_RENDER_PREFIX[$ext]='...' to override.\n"
        INPUT_PREFIX='##'
    fi
    shlog -l info "Rendering '$renderfile' by prefix '$INPUT_PREFIX'"
    grep "^\s*$INPUT_PREFIX" "$1" | sed "s/^\s*$INPUT_PREFIX//"
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]];then
    shrender-prefix "$@"
else
    export -f shrender-prefix
fi
